### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xfl03** [zlainsama/OfflineSkins#1]
Dear Author:
In my opinion, [crafatar](https://crafatar.com/) is just a 3rd-part skin mirror.
Why don't you use official [Mojang API](http://wiki.vg/Mojang_API)?

**Comment by zlainsama** [comment]
Because there are limitations in Mojang API and it often fails in China(I live in China), crafatar can handle those for me.
And in OfflineSkins, Mojang API is still used by the game, the mod just provide another image(through crafatar or local files) when it does't work.

**Comment by xfl03** [comment]
When playing in Offline mode server, Official Player's Profile could not be sent to others.
It is the reason why skin could not appeared in Offline server.
To fix this, just use Mojang API to get profile is enough.
 In this manner, 'authlib' could be used for parse JSON.

在离线服务器中之所以不能正常显示玩家的正版皮肤，是因为玩家的Profile没有被传递到其他玩家。
只需要根据用户名重新使用Mojang API获取Profile不就可以了么？
用这种方式的话，可以直接使用authlib来解析JSON。
——翻译不好请见谅
