### ISSUE TITLE
a question with this mod

### ISSUE THREAD

**Issue by Qie2035** [zlainsama/OfflineSkins#14]
First,are you chinese pesion?if you are,please add my qq:1546068251

**Comment by Qie2035** [comment]
if not,please tell me at here

**Comment by zlainsama** [comment]
没错，我是中国人。
有什么问题你直接问就好。

**Comment by Qie2035** [comment]
好的…
我在用1.12.1的MineLittlePony的mod时这个mod并不能换皮肤(那个mod是liteloader的)

**Comment by Qie2035** [comment]
(我竟然还傻到在邮件里回复…)

**Comment by zlainsama** [comment]
我并没有使用过MineLittlePony，你可以更加详细的描述下发生/没发生的现象么？

**Comment by Qie2035** [comment]
发生：使用了MineLittlePony默认的皮肤加载
没发生：使用OfflineSkins的皮肤加载
(我怀疑是mod加载优先级的问题)

**Comment by Qie2035** [comment]
所以说我们能不能用QQ交流一下…这里很不方便…我也着急…

**Comment by Qie2035** [comment]
要不然你就把这个mod的ResourceLocation改成用username的，不用UUID。

**Comment by Qie2035** [comment]
username就是玩家id(玩家名)

**Comment by Qie2035** [comment]
或者直接就用steve
