### ISSUE TITLE
Question about player models and HD skins

### ISSUE THREAD

**Issue by C0rn3j** [zlainsama/OfflineSkins#16]
Hiya, how does this mod know whether to use the Alex or Steve skin? Is it implemented even?

---

Also one more thing - would you consider implementing rendering of higher res skins? Since custom servers are now allowed it'd be an interesting addition.

I'm talking about skins like this, the only mod allowing this I found is for 1.7.10 or earlier.

![6031403ae7e031a2a0239631e7bb0908](https://user-images.githubusercontent.com/1641362/32123408-586e734e-bb64-11e7-80dd-d98b47cf6f67.png)

---

One more thing - If I wanted to PM/IM you, where could I reach you? ^^

**Comment by zlainsama** [comment]
Currently, the mod checks a specific pixel to see if it is transparent or not to determine which model to use.
`if (((image.getRGB(55, 20) & 0xFF000000) >>> 24) == 0) return "slim"; else return "default";`
About hires skins, they don't really fit into normal minecraft theme and they require extra codes to implement.(Also custom skin servers) That's why i did't implement them before.

If you want to PM me, you can PM me on curseforge. I will try to check them regularly.

**Comment by C0rn3j** [comment]
>Currently, the mod checks a specific pixel to see if it is transparent or not to determine which model to use.

Smart! Could you add this somewhere? Perhaps as a config comment? ^^

Also I'm not sure if this is totally compatible with most skins? Perhaps querying a text file first would be a better idea and you could use the current method as a fallback if it doesn't exist? e.g. /skins/C0rn3j.txt 
which would have 1 or 0, or Axel or Steve or whatever.

>they don't really fit into normal minecraft theme 

In the vanilla with no resource pack/shaders perhaps, but if you add any of these, it's the characters that may start to look unfitting. I think it really depends on the players.

>and they require extra codes to implement.(Also custom skin servers) That's why i did't implement them before.

About custom skin servers, yeah, I imagine this is not going to be the most used feature (or maybe it will, what do I know, people may suddenly take interest now that a feature like this will be available).

Would you consider implementing this anyways? ^^

If this can be done I wouldn't mind throwing a few $ your way(granted we can figure a way out to do that since you live in China), it seems like a cool feature to have.

**Comment by zlainsama** [comment]
High resolution skin support has been implemented.
![image](https://user-images.githubusercontent.com/3251859/32233745-12408ba2-be96-11e7-8a5b-c8b461b0ae5a.png)
I will be releasing this after i'm done with other things.

**Comment by C0rn3j** [comment]
That is awesome! Does it work for capes too? Are there any limitations?

Also do you use BTC/ZEC/Paypal?

**Comment by zlainsama** [comment]
It should work with capes.
You can't use smaller resolution and odd numbers might cause problems.

Image's height needs to be half of it's width or equal to it's width.
If you want to use slim model, you will need to use the new format Mojang introduced. (height equals to width)
It will work best if the provided image's width is divisible by 64.

Currently i don't use them. And i don't want to accept any money.
If i change my mind later, i will put a donation link in the curseforge project page.

**Comment by zlainsama** [comment]
1.12.2-v3 has been released.

**Comment by zlainsama** [comment]
@xfl03 
No.
"default" means a model like steve.
"slim" means a model like alex.
"legacy" is just a tag i used for pre-1.8 skin files, but it doesn't do anything because they are converted to newer format anyways.

**Comment by zlainsama** [comment]
@xfl03 
They are "default" after conversion.
https://github.com/zlainsama/OfflineSkins/blob/master/src/main/java/lain/mods/skins/providers/MojangCachedSkinProvider.java#L68-L77

**Comment by C0rn3j** [comment]
Closing this as my request was implemented years ago.
