### ISSUE TITLE
Forge throws WARNs about versioning/metadata

### ISSUE THREAD

**Issue by C0rn3j** [zlainsama/OfflineSkins#17]
[11:46:34] [main/WARN] [FML]: The coremod lain.mods.skins.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[22:19:31] [main/WARN] [offlineskins]: Mod offlineskins is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-v2

Apparently these things will be enforced in Forge 1.13 so you may as well fix it now to avoid having it annoy you later ^^

**Comment by zlainsama** [comment]
I did try to add one for my mods before. But i couldn't find any information about it.
Could you point me to a proper documentation?

**Comment by C0rn3j** [comment]
"MCVersion annotation forge documentation" <- googling this brought me here
https://mcforge.readthedocs.io/en/latest/gettingstarted/structuring/

which seems like what you need

**Comment by zlainsama** [comment]
This is actually a different thing to what i thought you were referring. I thought you were talking about version.properties.
About MCVersion annotation in coremod, I need it to be missing/empty to make a single coremod load on multiple minecraft versions. (If a version is specified in this annotation, the coremod won't load on any other minecraft versions even if they are subversions)
About missing element 'version', it was purposely left undefined to make use of mcmod.info's metadata, the warning can be safely ignored.

**Comment by C0rn3j** [comment]
> I need it to be missing/empty to make a single coremod load on multiple minecraft versions.

How about just throwing 1.12 all the way to 1.12.5 to it? Would still work on all 1.12.x versions and would get rid of the annoying warning I assume. Or perhaps I'm misunderstanding this.

>This is actually a different thing to what i thought you were referring. I thought you were talking about version.properties.

There seem to be 2 errors, I accidentally created issue with only one of them and edited it later.

**Comment by zlainsama** [comment]
If i put a version string in that, forge will try to match it with current minecraft version, if they match exactly(1.12 and 1.12.2 does not match), then forge will load the coremod, otherwise no. And a version range doesn't work.

**Comment by C0rn3j** [comment]
Doesn't look like this is an issue in 2020 on 1.16.1 anymore
