### ISSUE TITLE
Incompatibility with galacticraft inventory render

### ISSUE THREAD

**Issue by Aang23** [zlainsama/OfflineSkins#21]
[latest.log](https://github.com/zlainsama/OfflineSkins/files/1755964/latest.log)
[crash-2018-02-25_13.21.15-client.txt](https://github.com/zlainsama/OfflineSkins/files/1755966/crash-2018-02-25_13.21.15-client.txt)
Galacticraft uses a custom render solution for it's inventory, but that is not working anymore now.
I will report this to galacticraft too.

**Comment by zlainsama** [comment]
Closed as the code base has changed a lot since 1.12.2-v3a, and related code no longer exists.
Open a new issue if you need to.
