### ISSUE TITLE
1.7.10 java.lang.NoSuchFieldError: images

### ISSUE THREAD

**Issue by Llorx** [zlainsama/OfflineSkins#23]
That's it. WHen you launch this mod in a 1.7.10 server, this error is shown:

    java.lang.NoSuchFieldError: images at lain.mods.skins.OfflineSkins.<clinit>(OfflineSkins.java:125)

**Comment by xfl03** [comment]
> This mod is **Client-Only**, you **don't** need to install on server.

That's what author said in the post :)
