### ISSUE TITLE
What causing this ?

### ISSUE THREAD

**Issue by dewobedil** [zlainsama/OfflineSkins#27]
My modpack cant create world  and crashed, im wondering why this is happen
https://paste.dimdev.org/vacajopuqo.mccrash

**Comment by zlainsama** [comment]
You need to clear previous coremod extracted by the mod.
It is in the /mods/1.12.2 folder, delete any version that is older than the current version.

**Comment by Pythonic-Rainbow** [comment]
Ye, fixed.
