### ISSUE TITLE
broken skin

### ISSUE THREAD

**Issue by mattanatior97** [zlainsama/OfflineSkins#32]
if i uninstall the mod my skin shows up as Steve's when i,am online instead of my skin

**Comment by zlainsama** [comment]
if you uninstalled the mod, and the skin didn't show up normally, you should check your internet connection.

**Comment by mattanatior97** [comment]
My skin shows in other versions

**Comment by zlainsama** [comment]
which version of Minecraft are you on? did you try without any mods?

**Comment by mattanatior97** [comment]
Iam on 1.12.2 and the skin dosen't show in vanilla 1.12.2

**Comment by zlainsama** [comment]
does other players' skin show up when you are on a server?
you might reached the limit of a client can query about a user profile for information like skins.
try again in the next day to see if this problem persists.

**Comment by mattanatior97** [comment]
It been like this for a while now

**Comment by zlainsama** [comment]
hmm, have you tried re-install Minecraft? deleting/moving all files in .minecraft folder and let the launcher download them again.

**Comment by mattanatior97** [comment]
It worked

**Comment by zlainsama** [comment]
nice to hear that
