### ISSUE TITLE
offline skin [1.16.1-fabric] mod conflict with just map and offline skins

### ISSUE THREAD

**Issue by SDUBZ** [zlainsama/OfflineSkins#39]
OfflineSkins-1.16.1-v1-fabric.jar

justmap-1.1.90-1.16.1-unlimited

report : 
https://gist.github.com/SDUBZ/d5ca75be8f465ea6bc64101df5ac85cf

**Comment by Bulldog83** [comment]
In Just Map I use `ResourceTexture` to load player skins. I made some changes to get around using `PlayerSkinTexture`, but for compatibility it need to extends `CustomSkinTexture` from `ResourceTexture`.
