### ISSUE TITLE
Request: compatibility with [Ears] mod

### ISSUE THREAD

**Issue by agr21** [zlainsama/OfflineSkins#47]
I would like to request compatibility with "Ears" mod,as its not compatible as of now(newest version of  each). thank you so much! 
https://www.curseforge.com/minecraft/mc-mods/ears

**Comment by zlainsama** [comment]
Sorry about the late reply.
I would like to add support for it but OfflineSkins has support for high-definition skins which is most likely not compatible with Ears mod.

**Comment by agr21** [comment]
i understand,thank you for the reply
