### ISSUE TITLE
Misplaced textures when reloading resource packs

### ISSUE THREAD

**Issue by Hex4Nova** [zlainsama/OfflineSkins#49]
After a seemingly arbitrary amount of resource pack changes and reloads (F3+T) since game launch, textures begin to be misplaced and misassigned. This mostly concerns player skins and capes, but also UI elements and blocks in some cases, forcing a relaunch in order to fix all the textures.

I'm using MultiMC 5 and play on online servers, with Fabric Loader version 0.11.6. This error persists even with only OfflineSkins (1.17.1-v1-fabric) and Fabric API (0.37.1+1.17) active, although it appears to take longer to reproduce the bug compared to when I have other mods running. The bug seems to be easiest reproduced in a server with many plugins and/or have server resource packs, but once occurred it will quickly worsen regardless of multiplayer or integrated server.

![2021-07-30_10 34 54](https://user-images.githubusercontent.com/39517192/127650247-7b89e08a-89d4-41f5-a0fa-b1cdb2536e75.png)

![2021-07-30_10 35 37](https://user-images.githubusercontent.com/39517192/127650275-be481f25-49f3-4344-ac45-250f816406f2.png)
The above screenshots were taken in the same singleplayer world without going back to the menu. The second was taken after another use of F3+T since the first. At the time of these screenshots, I was still running some client-side optimization mods.

![2021-07-30_13 46 23](https://user-images.githubusercontent.com/39517192/127650987-1bb52011-0133-43b3-81b5-76e801b6647a.png)

![2021-07-30_14 05 50](https://user-images.githubusercontent.com/39517192/127650830-d46f9251-328f-48be-9c30-b020b58ac9c4.png)
The above screenshots were taken in the lobbies of servers Hypixel and Minehut respectively. This block texture glitch occurred seemingly without any input - I had changed resource packs after the screenshot at Hypixel, but the glitch appeared minutes later. Only OfflineSkins and Fabric API were loaded.

![2021-07-30_14 18 39](https://user-images.githubusercontent.com/39517192/127652019-3a1398cf-2ba0-4580-bfea-6a398d5f09e0.png)
A screenshot in the same singleplayer world as earlier, of what I assume to be the vignette texture being replaced along with the sun by player skin textures. All three groups of screenshots are from three different sessions.

In addition to having my username as filename and placing it in the right folder (as per the instructions on the curseforge page), I also have copies of my skin and custom cape stored in the respective "uuid" folder, named in both my usual uuid and my uuid without minus signs. This latter effort did not appear to have an effect on the problem.
![image](https://user-images.githubusercontent.com/39517192/127652501-860ba029-e58c-40f2-846d-ab856f648367.png)

Let me know if there's anything I can do to help.

**Comment by zlainsama** [comment]
Could you test if this happens on the forge version? also how many memory do you allocate? and does this happen in older minecraft versions like 1.16.5?

**Comment by Hex4Nova** [comment]
The screenshots above were taken with allocated memory of minimum 512 MB and max 3072MB, and permgen 128 MB. I was still able to reproduce the bug when I launched the same instance with min 2048 MB, max 4096 MB and permgen 128 MB.

The bug still happens when launched via the vanilla launcher. (Fabric 0.11.6 for Minecraft 1.17.1)

Here's a screenshot of the game log whenever the bug occurs. This repeats several times on each occurrence.
![image](https://user-images.githubusercontent.com/39517192/127737326-2d156c71-10ae-494d-bb98-eaf117b47cce.png)

I couldn't get Forge to work on 1.17.1, so I tried 1.16.5 via MultiMC. The bug does not seem to happen on Forge 1.16.5, but it did happen when I tried on Fabric 1.16.5. I haven't tested how bad it can get, just whether any texture gets swapped at all.

**Comment by zlainsama** [comment]
I couldn't reproduce this in my environment, I tried F3+T over 20 times, everything still normal.
How many reloads do you need for this to happen? and do your reloads take longer than 15 seconds? how many CPU cores do you have?
The mod has a cache of 15 seconds, if no access in this time period, it will discard any loaded SkinData that exceeds this limit.
Normally, the mod registers a TickListener to refresh this cache for all loaded players so their SkinData don't get discarded too often, this TickListener's behavior might be different on Fabric than Forge.

**Comment by zlainsama** [comment]
Could you try this [version](https://github.com/zlainsama/OfflineSkins/releases/download/1.17.1-v2-fabric/OfflineSkins-1.17.1-v2-fabric.jar)?

**Comment by Hex4Nova** [comment]
New version seems to work just fine. Tested it out in a couple places with server resource packs that would have messed up the textures in older versions, haven't ran into any issues after 10 min. Awesome, thanks!
