### ISSUE TITLE
Request: Support 3D Skin Layers

### ISSUE THREAD

**Issue by luni3359** [zlainsama/OfflineSkins#57]
Currently having both mods active makes Offline Skins override 3D Skin Layers.

**Comment by zlainsama** [comment]
Which version?

**Comment by luni3359** [comment]
3d skin layers 1.4.3 (fabric)
OfflineSkins 1.18.2-v1

**Comment by zlainsama** [comment]
It was compatible in 1.16.5 forge.
After some looking into their(3D Skin Layers mod) code, I think this is caused by their new ways to acquire texture information.
It is possible for me to provide a standard texture instance but that involves writing the skin file once more onto the storage device.

**Comment by zlainsama** [comment]
Fixed in 1.18.2-v2 and 1.18.2-v2-fabric.
