### ISSUE TITLE
No player model shadow w/ Shaders

### ISSUE THREAD

**Issue by CasualGeorge** [zlainsama/OfflineSkins#63]
I am using Complementary Shaders for mc version 1.19.2, and there is no first-person player model shadow. The mod is definitely still worth using, but it does slightly compromise the experience. It should be noted that the weapon shadow is present when attacking, but there is no casted shadow from the player themselves. Third-person mode does not apply.

**Comment by zlainsama** [comment]
I just tested **ComplementaryShaders_v4.5** with **OptiFine_1.19.2_HD_U_H9** and **oculus-mc1.19.2-1.2.8a**, first-person player model shadow is properly displayed on my end.
I think there is some other mods in your installation doing optimization too aggressive?

**Comment by CasualGeorge** [comment]
Thank you!

**Comment by CasualGeorge** [comment]
FYI, I just did some troubleshooting with different shader-packs. It appears that using them on Fabric with the Iris mod does not render the first-person shadow. Thanks, again!
