### ISSUE TITLE
[1.10.2] Server crash on load

### ISSUE THREAD

**Issue by c0rn3j** [zlainsama/OfflineSkins#7]
I assume the mod is not supposed to be in the server mods folder, as it works just fine in client. I'm used to throwing all my 50~ mods in the server folder not caring whether they're client side only or server side too, because it'd be too tedious to sort.

Could a check be added to allow having the .jar file in the server mods folder?

http://pastebin.com/JpkAeyRN

**Comment by zlainsama** [comment]
This was a mistake I made when I was fixing issue #4 
It will be fixed in next release.
