### ISSUE TITLE
[1.10.2] head items use the default skin

### ISSUE THREAD

**Issue by C0rn3j** [zlainsama/OfflineSkins#8]
http://i.imgur.com/7vSo2zk.png

**Comment by zlainsama** [comment]
http://i.imgur.com/gSdtLRD.png

The mod does not provide skins for skulls. But the skull should still render skins even if the server is in offline mode provided that the skull has a valid player profile, both server and client needs a working connection to mojang's server.

**Comment by c0rn3j** [comment]
Weirdly skulls don't render for us. The server is in offline mode and all players are based in EU, yet nobody can see them.

**Comment by zlainsama** [comment]
a new version for 1.11 has been released to support player skulls in offline mode.
it will be back ported to 1.10.
